apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ## DEFAULT SERVICE TYPE IS CLUSTER-IP
  ## When using docker-desktop, externalIp = localhost, 127.0.0.1
  type: LoadBalancer
  selector:
    app: myweb
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 80
