apiVersion: v1
kind: Pod
metadata:
    name: pod1
    namespace: mahendra
    labels:
      name: myapp1
spec:
    nodeSelector:
      kubernetes.io/os: linux
    containers:
    - name: web1
      image: mahendrshinde/myweb:latest
      resources:
        limits:
            memory: "64Mi"
            cpu: "100m"
      ports:
      - containerPort: 80
